# Test Emulated Performance

Test the `get_emulated` method and calculate Cartesian performance across all trajectories.

In [1]:
# !pip install dtw-python

In [2]:
from testers import Tester

In [3]:
t = Tester()

Tester loaded dataset with shape: (11, 299, 35)
from this path /home/arash/catkin_ws/src/feedback_controller/fbc/neural_network/data/torobo/trajs:72_blocks:3_triangle_v_scarce/test_interp_0.85.npy
No data file named /home/erhan/catkin_ws/src/erhtor_work/tormain/Resources/larm60.txt
bodypart structure for larm is constructed.
No data file named /home/erhan/catkin_ws/src/erhtor_work/tormain/Resources/rarm60.txt
bodypart structure for rarm is constructed.
bodypart structure for head is constructed.


In [4]:
t.load_model(train_no=0, epoch_no=10000, use_custom_loss=False, model_complexity='high')

***
Loaded model weights from /home/arash/catkin_ws/src/feedback_controller/fbc/neural_network/weights/trajs:72_blocks:3_triangle_v_scarce|interp_0.85|mse_los|tar_cart|robo_enc_eef_N=4_plus_joints_noise=0.1_only6|40.739K_params/train_no_0/fbc_10000.pth
Loaded baseline weights from /home/arash/catkin_ws/src/feedback_controller/fbc/neural_network/weights/trajs:72_blocks:3_triangle_v_scarce|interp_0.85|mse_los|tar_cart|base|CONC_robo_enc_eef_N=4_plus_joints_noise=0.1_only6|40.799K_params/train_no_0/fbc_10000.pth


In [ ]:
# Test Cartesian performance and DTW across all trajectories
score, avg_dtw, avg_dtw_norm = t.calculate_cartesian_perform_with_dtw(use_baseline=True)
print(f'Cartesian performance: {score}%')
print(f'Average DTW distance: {avg_dtw}')
print(f'Average normalized DTW distance: {avg_dtw_norm}')

In [5]:
# loop
epoch_no = 7000
all_scores = []
all_dtws = []
all_dtw_norms = []
for i in range(3):
    t.load_model(train_no=i, epoch_no=epoch_no, use_custom_loss=False, model_complexity='high')
    score, avg_dtw, avg_dtw_norm = t.calculate_cartesian_perform_with_dtw(use_baseline=True)
    all_scores.append(score)
    all_dtws.append(avg_dtw)
    all_dtw_norms.append(avg_dtw_norm)
    print(f'Train {i}: score={score:.4f}, DTW={avg_dtw:.4f}, DTW_norm={avg_dtw_norm:.4f}')

***
Loaded model weights from /home/arash/catkin_ws/src/feedback_controller/fbc/neural_network/weights/trajs:72_blocks:3_triangle_v_scarce|interp_0.85|mse_los|tar_cart|robo_enc_eef_N=4_plus_joints_noise=0.1_only6|40.739K_params/train_no_0/fbc_7000.pth
Loaded baseline weights from /home/arash/catkin_ws/src/feedback_controller/fbc/neural_network/weights/trajs:72_blocks:3_triangle_v_scarce|interp_0.85|mse_los|tar_cart|base|CONC_robo_enc_eef_N=4_plus_joints_noise=0.1_only6|40.799K_params/train_no_0/fbc_7000.pth
Importing the dtw module. When using in academic works please cite:
  T. Giorgino. Computing and Visualizing Dynamic Time Warping Alignments in R: The dtw Package.
  J. Stat. Soft., doi:10.18637/jss.v031.i07.

Train 0: score=0.7955, DTW=20.7218, DTW_norm=0.0347
***
Loaded model weights from /home/arash/catkin_ws/src/feedback_controller/fbc/neural_network/weights/trajs:72_blocks:3_triangle_v_scarce|interp_0.85|mse_los|tar_cart|robo_enc_eef_N=4_plus_joints_noise=0.1_only6|40.739K_para

In [6]:
import numpy as np

all_scores = np.array(all_scores)
print(all_scores)
print(np.mean(all_scores))
print(np.std(all_scores))

print("===")
all_dtws = np.array(all_dtws)
print(all_dtws)
print(np.mean(all_dtws))
print(np.std(all_dtws))

[0.79545455 0.52272727 0.65909091]
0.6590909090909091
0.11134044285378082
===
[20.72181118 69.16306858 53.47241507]
47.7857649412442
20.18072259725216


In [7]:
# loop
epoch_no = 7000
all_scores = []
all_dtws = []
all_dtw_norms = []
for i in range(3):
    t.load_model(train_no=i, epoch_no=epoch_no, use_custom_loss=False, model_complexity='high')
    score, avg_dtw, avg_dtw_norm = t.calculate_cartesian_perform_with_dtw(use_baseline=False)
    all_scores.append(score)
    all_dtws.append(avg_dtw)
    all_dtw_norms.append(avg_dtw_norm)
    print(f'Train {i}: score={score:.4f}, DTW={avg_dtw:.4f}, DTW_norm={avg_dtw_norm:.4f}')

***
Loaded model weights from /home/arash/catkin_ws/src/feedback_controller/fbc/neural_network/weights/trajs:72_blocks:3_triangle_v_scarce|interp_0.85|mse_los|tar_cart|robo_enc_eef_N=4_plus_joints_noise=0.1_only6|40.739K_params/train_no_0/fbc_7000.pth
Loaded baseline weights from /home/arash/catkin_ws/src/feedback_controller/fbc/neural_network/weights/trajs:72_blocks:3_triangle_v_scarce|interp_0.85|mse_los|tar_cart|base|CONC_robo_enc_eef_N=4_plus_joints_noise=0.1_only6|40.799K_params/train_no_0/fbc_7000.pth
Train 0: score=0.5455, DTW=50.0946, DTW_norm=0.0838
***
Loaded model weights from /home/arash/catkin_ws/src/feedback_controller/fbc/neural_network/weights/trajs:72_blocks:3_triangle_v_scarce|interp_0.85|mse_los|tar_cart|robo_enc_eef_N=4_plus_joints_noise=0.1_only6|40.739K_params/train_no_1/fbc_7000.pth
Loaded baseline weights from /home/arash/catkin_ws/src/feedback_controller/fbc/neural_network/weights/trajs:72_blocks:3_triangle_v_scarce|interp_0.85|mse_los|tar_cart|base|CONC_robo_e

In [8]:
import numpy as np

all_scores = np.array(all_scores)
print(all_scores)
print(np.mean(all_scores))
print(np.std(all_scores))

print("===")
all_dtws = np.array(all_dtws)
print(all_dtws)
print(np.mean(all_dtws))
print(np.std(all_dtws))

[0.54545455 0.45454545 0.63636364]
0.5454545454545454
0.07422696190252055
===
[50.09463778 88.29564129 36.91953019]
58.43660308830104
21.787878690620527


In [ ]:
# Cartesian performance: 72.7%

# In train set, with decreasing epoch_no, the performance decreases as well. 

# In test set, maybe.

In [ ]:
# With joints only, around 30%. 